---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by weihao.lv.
--- DateTime: 2021/5/26 2:56 下午
--- 可重入加锁

-- 加锁
-- 加锁键
local lockKey = KEYS[1]
-- 代表重入请求的唯一 id
local requestId = ARGV[1]

if redis.call('EXISTS', lockKey) ~= 0 then
    local lockTable = redis.call("HMGET", lockKey, 'requestId', 'count')
    if (requestId ~= lockTable[1]) then
        return 0
    else
        redis.call('HMSET', lockKey, 'count', lockTable[2] + 1)
        return 1
    end
else
    redis.call("HMSET", lockKey, 'requestId', requestId, 'count', 1)
    redis.call("EXPIRE", lockKey, 30)
    return 1
end

